### ISSUE TITLE
Adding failureReason to Operation update

### ISSUE THREAD

**Issue by f11h** [cloud-of-things/cot-java-rest-sdk#51]
Updating an Operation just PUT's the new status to CoT.
It would be great to be able to set a "failureReason" wich is displayed in operation audit.

**Comment by rokkbert** [comment]
The SDK doesn't support that because here http://cumulocity.com/guides/reference/device-control/ it says for failureReason "No" in the column PUT/POST. So the question is... how is that reason supposed to reach the CoT? Maybe that is just a mistake in the documentation? We need to try it, I guess.

**Comment by f11h** [comment]
Have a look into Cumulocity's Postman API. There the "Fail operation" request has an failureReason attribute and it will be displayed in CoT Devicemanagement.

![image](https://user-images.githubusercontent.com/31076102/32342077-abc317ee-bfff-11e7-85a7-47ac2254979c.png)

![image](https://user-images.githubusercontent.com/31076102/32342200-fbfe8086-bfff-11e7-9259-a0d35c21cc2f.png)

**Comment by rokkbert** [comment]
Ah, cool. We didn't try that. But if that's how it works then I would consider that a very likely feature for the next release of the SDK.

**Comment by f11h** [comment]
It looks like there is a generaly redesign of this part of the SDK required.
Do you know the CoT log file request feature?
Requesting log files from a device is done with an operation, too. The device uploads the log file as as binary and adds a link to the binary in operations details when it sets it to "SUCCESSFUL". I guess at the moment this is even not possible with SDK.

I've attached a screenshot of an operation with an associated binary object.
![image](https://user-images.githubusercontent.com/31076102/32380444-5ca28bf2-c0b0-11e7-86bd-418c0e2d5065.png)

**Comment by rokkbert** [comment]
No, it's not possible. But that is only because all the extra fields are ignored from the operation. We can upgrade it to only strip the fields that are known to be invalid in the update, and just pass on all unknown fields, like failure reasons, results or log file links. That would not require any major redesigning. Can't promise when this will happen though.

**Comment by Andyck** [comment]
This issue is fixed and released in version 1.0.4
