### ISSUE TITLE
JsonArray pagination is not efficient

### ISSUE THREAD

**Issue by rokkbert** [cloud-of-things/cot-java-rest-sdk#72]
Currently it seems that the existence of a "next" page is determined by the availability of the next ressource. Before doing that request we might check for totalPages (optional, but could be there) and if the number of elements on the current page is < the pageSize, in which case no next page will exist.

http://cumulocity.com/guides/reference/rest-implementation/

**Comment by Matthimatiker** [comment]
This should have been fixed by pull request #73.
